### ISSUE TITLE
DriveTank command `end` method not being called properly

### ISSUE THREAD

**Issue by ky28059** [grt192/GRTCommandBased#3]
https://github.com/grt192/GRTCommandBased/blob/develop/src/main/java/frc/robot/commands/tank/DriveTankCommand.java#L48-L50
This function should be an `@Override` and take in a `boolean`: [docs](https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj2/command/Command.html#end(boolean))

**Comment by proan** [comment]
If you work on this (which would be great), please make your changes in a branch and open a pull request to bring them back into main. This way we can review your code together.
